# 配置环境
spring:
  profiles:
    active: prod
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://localhost:3306/springboot?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
     username: root
     password: root
  # jpa配置
  jpa:
    hibernate:
      # create:在数据库建表 update代表更新表 ，首次启动需要创建表
      ddl-auto: update
    show-sql: true

# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /springboot
# 自定义配置信息
girl:
  name: B
  age: 18
  content: content:${girl.name},age:${girl.age}