# 拉取基础镜像
FROM 139.199.32.44:2375/java
# 维者信息
MAINTAINER pibigstar

# 将JDK复制到镜像中，如果镜像已经有了JDK环境则无需配置此项和下面的运行环境
# COPY jdk1.7.0_79 /usr/local/jdk1.7.0_79
# 配置运行环境
# ENV JAVA_HOME=/usr/local/jdk1.7.0_79
# ENV PATH=$JAVA_HOME/bin:$PATH
# ENV CLASSPATH=.:$JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar

# 添加springboot项目到镜像中的home目录，并重命名为app.jar
ADD spring-boot-docker-0.0.1-SNAPSHOT.jar ~/app.jar

# 告诉Docker服务端暴露的端口，在容器启动时需要通过 -p 做端口映射
EXPOSE 8080

# 容器启动后执行的命令
ENTRYPOINT ["java","-jar","~/app.jar"]